### ISSUE TITLE
CO2

### ISSUE THREAD

**Issue by Puzzledyy** [enjeeneer/PEARL#1]
Hello, I think this is a very useful program and will help me a lot, but I would like to ask you where the CO2 data here comes from? Is it calculated? You are using energym environment, so I am not sure how your co2 value is calculated, so I would like to ask you.

**Comment by Puzzledyy** [comment]
I have just done some research on this and you see that the project does not use the RL model for prediction, right? You just calculated his loss value, maybe I misunderstood it, I hope you can reply, thanks!

**Comment by enjeeneer** [comment]
@Puzzledyy Sorry I'm just replying, I completely missed this. The CO2 data is taken from [here](https://app.electricitymaps.com/map), and matches the true data for the year simulated by Energym. It's appended to the state space and fed to the agent at each timestep. PEARL _does_ predict grid CO2 in its rollouts, but of course, these predictions are conditioned on the grid CO2 data it has seen in previous states.

I'm updating the paper to make this more clear, and I should really add this to the README because you're not the first person to raise this. Thanks for checking out the repo!
